"""initial

Revision ID: 2b811c4a0025
Revises: 
Create Date: 2026-05-07 14:35:23.522194
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '2b811c4a0025'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_settings', 'provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='glm | openai | local',
               existing_nullable=False,
               existing_server_default=sa.text("'local'"))
    op.alter_column('ai_settings', 'openai_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='OpenAI Key',
               existing_nullable=True)
    op.alter_column('ai_settings', 'openai_model',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='OpenAI æ¨¡åž‹',
               existing_nullable=True)
    op.alter_column('ai_settings', 'zhipu_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='æ™ºè°±GLM Key',
               existing_nullable=True)
    op.alter_column('ai_settings', 'zhipu_model',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='æ™ºè°±GLM æ¨¡åž‹',
               existing_nullable=True)
    op.alter_column('ai_settings', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('case_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='ç±»åˆ«å\x90\x8dç§°',
               existing_nullable=False)
    op.alter_column('case_categories', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ç±»åˆ«æ\x8f\x8fè¿°',
               existing_nullable=True)
    op.alter_column('case_categories', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('cases', 'category_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç±»åˆ«ID',
               existing_nullable=False)
    op.alter_column('cases', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='æ¡ˆä¾‹æ\xa0‡é¢˜',
               existing_nullable=False)
    op.alter_column('cases', 'case_guide',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='æ¡ˆä¾‹æŒ‡å¼•',
               existing_nullable=True)
    op.alter_column('cases', 'site_info',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='ç«™ç‚¹ä¿¡æ\x81¯',
               existing_nullable=True)
    op.alter_column('cases', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='åŽŸå§‹æ–‡æ¡£è·¯å¾„',
               existing_nullable=True)
    op.alter_column('cases', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('cases', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('comment_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('comment_likes', 'comment_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='è¯„è®ºID',
               existing_nullable=False)
    op.alter_column('comment_likes', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comment_reports', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ä¸¾æŠ¥ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('comment_reports', 'comment_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='è¢«ä¸¾æŠ¥è¯„è®ºID',
               existing_nullable=False)
    op.alter_column('comment_reports', 'reason',
               existing_type=mysql.ENUM('spam', 'inappropriate', 'offensive', 'other', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ä¸¾æŠ¥åŽŸå›\xa0',
               existing_nullable=False)
    op.alter_column('comment_reports', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ä¸¾æŠ¥è¯¦æƒ…',
               existing_nullable=True)
    op.alter_column('comment_reports', 'status',
               existing_type=mysql.ENUM('pending', 'reviewed', 'resolved', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='å¤„ç\x90†çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('comment_reports', 'admin_note',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ç®¡ç\x90†å‘˜å¤„ç\x90†æ„\x8fè§\x81',
               existing_nullable=True)
    op.alter_column('comment_reports', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comment_reports', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('comments', 'content_type',
               existing_type=mysql.ENUM('station_answer', 'knowledge_answer', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è¯„è®ºå†…å®¹ç±»åž‹',
               existing_nullable=False)
    op.alter_column('comments', 'content_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='å…³è\x81”çš„ç\xad”æ¡ˆID',
               existing_nullable=False)
    op.alter_column('comments', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è¯„è®ºå†…å®¹',
               existing_nullable=False)
    op.alter_column('comments', 'comment_type',
               existing_type=mysql.ENUM('comment', 'question', 'answer', 'suggestion', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è¯„è®ºç±»åž‹',
               existing_nullable=True,
               existing_server_default=sa.text("'comment'"))
    op.alter_column('comments', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='çˆ¶è¯„è®ºID',
               existing_nullable=True)
    op.alter_column('comments', 'likes_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç‚¹èµžæ•°',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'status',
               existing_type=mysql.ENUM('active', 'hidden', 'deleted', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('comments', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('exam_answers', 'exam_record_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='è€ƒè¯•è®°å½•ID',
               existing_nullable=False)
    op.alter_column('exam_answers', 'station_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('exam_answers', 'user_answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ç”¨æˆ·ç\xad”æ¡ˆ',
               existing_nullable=True)
    op.alter_column('exam_answers', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='å¾—åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('exam_answers', 'ai_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='AIè¯„ä»·å\x8f\x8dé¦ˆ',
               existing_nullable=True)
    op.drop_constraint(op.f('exam_answers_ibfk_1'), 'exam_answers', type_='foreignkey')
    op.create_foreign_key(None, 'exam_answers', 'exam_records', ['exam_record_id'], ['id'])
    op.alter_column('exam_questions', 'exam_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='è€ƒè¯•ID',
               existing_nullable=False)
    op.alter_column('exam_questions', 'station_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('exam_questions', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='é¢˜ç›®åˆ†å€¼',
               existing_nullable=True,
               existing_server_default=sa.text("'10.00'"))
    op.alter_column('exam_questions', 'order_index',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='é¢˜ç›®é¡ºåº\x8f',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(op.f('exam_questions_ibfk_1'), 'exam_questions', type_='foreignkey')
    op.create_foreign_key(None, 'exam_questions', 'exams', ['exam_id'], ['id'])
    op.alter_column('exam_records', 'exam_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='è€ƒè¯•ID',
               existing_nullable=False)
    op.alter_column('exam_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('exam_records', 'total_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='æ€»åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('exam_records', 'max_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='æ»¡åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'100.00'"))
    op.alter_column('exam_records', 'start_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='å¼€å§‹æ—¶é—´',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('exam_records', 'submit_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='æ\x8f\x90äº¤æ—¶é—´',
               existing_nullable=True)
    op.alter_column('exam_records', 'status',
               existing_type=mysql.ENUM('in_progress', 'submitted', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è€ƒè¯•çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'in_progress'"))
    op.alter_column('exams', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='è€ƒè¯•æ\xa0‡é¢˜',
               existing_nullable=False)
    op.alter_column('exams', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è€ƒè¯•æ\x8f\x8fè¿°',
               existing_nullable=True)
    op.alter_column('exams', 'creator_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='åˆ›å»ºè€…ID',
               existing_nullable=False)
    op.alter_column('exams', 'start_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='å¼€å§‹æ—¶é—´',
               existing_nullable=True)
    op.alter_column('exams', 'end_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='ç»“æ\x9dŸæ—¶é—´',
               existing_nullable=True)
    op.alter_column('exams', 'duration',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='è€ƒè¯•æ—¶é•¿(åˆ†é’Ÿ)',
               existing_nullable=True,
               existing_server_default=sa.text("'60'"))
    op.alter_column('exams', 'status',
               existing_type=mysql.ENUM('draft', 'published', 'ended', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è€ƒè¯•çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('exams', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('extended_knowledge', 'case_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='æ¡ˆä¾‹ID',
               existing_nullable=False)
    op.alter_column('extended_knowledge', 'question',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='æ‰©å±•çŸ¥è¯†é—®é¢˜',
               existing_nullable=False)
    op.alter_column('extended_knowledge', 'answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='æ‰©å±•çŸ¥è¯†ç\xad”æ¡ˆ',
               existing_nullable=False)
    op.alter_column('extended_knowledge', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('extended_knowledge_ibfk_1'), 'extended_knowledge', type_='foreignkey')
    op.create_foreign_key(None, 'extended_knowledge', 'cases', ['case_id'], ['id'])
    op.alter_column('learning_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('learning_records', 'station_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('learning_records', 'user_answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ç”¨æˆ·ç\xad”æ¡ˆ',
               existing_nullable=True)
    op.alter_column('learning_records', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='å¾—åˆ†',
               existing_nullable=True)
    op.alter_column('learning_records', 'max_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='æ»¡åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'100.00'"))
    op.alter_column('learning_records', 'ai_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='AIè¯„ä»·å\x8f\x8dé¦ˆ',
               existing_nullable=True)
    op.alter_column('learning_records', 'completed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('point_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('point_records', 'points',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç§¯åˆ†å\x8f˜åŒ–',
               existing_nullable=False)
    op.alter_column('point_records', 'reason',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='ç§¯åˆ†åŽŸå›\xa0',
               existing_nullable=True)
    op.alter_column('point_records', 'related_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='å…³è\x81”ID',
               existing_nullable=True)
    op.alter_column('point_records', 'related_type',
               existing_type=mysql.ENUM('learning', 'exam', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='å…³è\x81”ç±»åž‹',
               existing_nullable=True)
    op.alter_column('point_records', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('standard_answers', 'station_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('standard_answers', 'answer_item',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ç\xad”æ¡ˆé¡¹',
               existing_nullable=False)
    op.alter_column('standard_answers', 'score_weight',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='åˆ†å€¼æ\x9dƒé‡\x8d',
               existing_nullable=True,
               existing_server_default=sa.text("'1.00'"))
    op.alter_column('standard_answers', 'order_index',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç\xad”æ¡ˆé¡ºåº\x8f',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('standard_answers', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('standard_answers_ibfk_1'), 'standard_answers', type_='foreignkey')
    op.create_foreign_key(None, 'standard_answers', 'stations', ['station_id'], ['id'])
    op.alter_column('stations', 'case_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='æ¡ˆä¾‹ID',
               existing_nullable=False)
    op.alter_column('stations', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='ç«™ç‚¹å\x90\x8dç§°',
               existing_nullable=False)
    op.alter_column('stations', 'assessment_task',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è€ƒæ\xa0¸ä»»åŠ¡',
               existing_nullable=True)
    op.alter_column('stations', 'question',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='é—®é¢˜',
               existing_nullable=False)
    op.alter_column('stations', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('stations_ibfk_1'), 'stations', type_='foreignkey')
    op.create_foreign_key(None, 'stations', 'cases', ['case_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='ç”¨æˆ·å\x90\x8d',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='å¯†ç\xa0\x81å“ˆå¸Œ',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='é‚®ç®±',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='æ‰‹æœºå\x8f·',
               existing_nullable=True)
    op.alter_column('users', 'real_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='çœŸå®žå§“å\x90\x8d',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('nurse', 'admin', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è§’è‰²ï¼šæŠ¤å£«/ç®¡ç\x90†å‘˜',
               existing_nullable=False,
               existing_server_default=sa.text("'nurse'"))
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='æ‰€å±žç§‘å®¤',
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=mysql.ENUM('active', 'disabled', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è´¦å\x8f·çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('users', 'points',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç§¯åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('weakness_analysis', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('weakness_analysis', 'content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               comment=None,
               existing_comment='åˆ†æž\x90JSONæ–‡æœ¬',
               existing_nullable=False)
    op.alter_column('weakness_analysis', 'generated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('weakness_analysis_ibfk_1'), 'weakness_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'weakness_analysis', 'users', ['user_id'], ['id'])
    op.alter_column('wrong_questions', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('wrong_questions', 'station_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('wrong_questions', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment=None,
               existing_comment='å¾—åˆ†',
               existing_nullable=True)
    op.alter_column('wrong_questions', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wrong_questions', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('wrong_questions', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='å¾—åˆ†',
               existing_nullable=True)
    op.alter_column('wrong_questions', 'station_id',
               existing_type=mysql.INTEGER(),
               comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('wrong_questions', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.drop_constraint(None, 'weakness_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('weakness_analysis_ibfk_1'), 'weakness_analysis', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('weakness_analysis', 'generated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('weakness_analysis', 'content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment='åˆ†æž\x90JSONæ–‡æœ¬',
               existing_nullable=False)
    op.alter_column('weakness_analysis', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'points',
               existing_type=mysql.INTEGER(),
               comment='ç§¯åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'status',
               existing_type=mysql.ENUM('active', 'disabled', collation='utf8mb4_unicode_ci'),
               comment='è´¦å\x8f·çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='æ‰€å±žç§‘å®¤',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('nurse', 'admin', collation='utf8mb4_unicode_ci'),
               comment='è§’è‰²ï¼šæŠ¤å£«/ç®¡ç\x90†å‘˜',
               existing_nullable=False,
               existing_server_default=sa.text("'nurse'"))
    op.alter_column('users', 'real_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='çœŸå®žå§“å\x90\x8d',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='æ‰‹æœºå\x8f·',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='é‚®ç®±',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='å¯†ç\xa0\x81å“ˆå¸Œ',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='ç”¨æˆ·å\x90\x8d',
               existing_nullable=False)
    op.drop_constraint(None, 'stations', type_='foreignkey')
    op.create_foreign_key(op.f('stations_ibfk_1'), 'stations', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.alter_column('stations', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stations', 'question',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='é—®é¢˜',
               existing_nullable=False)
    op.alter_column('stations', 'assessment_task',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='è€ƒæ\xa0¸ä»»åŠ¡',
               existing_nullable=True)
    op.alter_column('stations', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='ç«™ç‚¹å\x90\x8dç§°',
               existing_nullable=False)
    op.alter_column('stations', 'case_id',
               existing_type=mysql.INTEGER(),
               comment='æ¡ˆä¾‹ID',
               existing_nullable=False)
    op.drop_constraint(None, 'standard_answers', type_='foreignkey')
    op.create_foreign_key(op.f('standard_answers_ibfk_1'), 'standard_answers', 'stations', ['station_id'], ['id'], ondelete='CASCADE')
    op.alter_column('standard_answers', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('standard_answers', 'order_index',
               existing_type=mysql.INTEGER(),
               comment='ç\xad”æ¡ˆé¡ºåº\x8f',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('standard_answers', 'score_weight',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='åˆ†å€¼æ\x9dƒé‡\x8d',
               existing_nullable=True,
               existing_server_default=sa.text("'1.00'"))
    op.alter_column('standard_answers', 'answer_item',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='ç\xad”æ¡ˆé¡¹',
               existing_nullable=False)
    op.alter_column('standard_answers', 'station_id',
               existing_type=mysql.INTEGER(),
               comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('point_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('point_records', 'related_type',
               existing_type=mysql.ENUM('learning', 'exam', collation='utf8mb4_unicode_ci'),
               comment='å…³è\x81”ç±»åž‹',
               existing_nullable=True)
    op.alter_column('point_records', 'related_id',
               existing_type=mysql.INTEGER(),
               comment='å…³è\x81”ID',
               existing_nullable=True)
    op.alter_column('point_records', 'reason',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='ç§¯åˆ†åŽŸå›\xa0',
               existing_nullable=True)
    op.alter_column('point_records', 'points',
               existing_type=mysql.INTEGER(),
               comment='ç§¯åˆ†å\x8f˜åŒ–',
               existing_nullable=False)
    op.alter_column('point_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('learning_records', 'completed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('learning_records', 'ai_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='AIè¯„ä»·å\x8f\x8dé¦ˆ',
               existing_nullable=True)
    op.alter_column('learning_records', 'max_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='æ»¡åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'100.00'"))
    op.alter_column('learning_records', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='å¾—åˆ†',
               existing_nullable=True)
    op.alter_column('learning_records', 'user_answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='ç”¨æˆ·ç\xad”æ¡ˆ',
               existing_nullable=True)
    op.alter_column('learning_records', 'station_id',
               existing_type=mysql.INTEGER(),
               comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('learning_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.drop_constraint(None, 'extended_knowledge', type_='foreignkey')
    op.create_foreign_key(op.f('extended_knowledge_ibfk_1'), 'extended_knowledge', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.alter_column('extended_knowledge', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('extended_knowledge', 'answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='æ‰©å±•çŸ¥è¯†ç\xad”æ¡ˆ',
               existing_nullable=False)
    op.alter_column('extended_knowledge', 'question',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='æ‰©å±•çŸ¥è¯†é—®é¢˜',
               existing_nullable=False)
    op.alter_column('extended_knowledge', 'case_id',
               existing_type=mysql.INTEGER(),
               comment='æ¡ˆä¾‹ID',
               existing_nullable=False)
    op.alter_column('exams', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('exams', 'status',
               existing_type=mysql.ENUM('draft', 'published', 'ended', collation='utf8mb4_unicode_ci'),
               comment='è€ƒè¯•çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('exams', 'duration',
               existing_type=mysql.INTEGER(),
               comment='è€ƒè¯•æ—¶é•¿(åˆ†é’Ÿ)',
               existing_nullable=True,
               existing_server_default=sa.text("'60'"))
    op.alter_column('exams', 'end_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='ç»“æ\x9dŸæ—¶é—´',
               existing_nullable=True)
    op.alter_column('exams', 'start_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='å¼€å§‹æ—¶é—´',
               existing_nullable=True)
    op.alter_column('exams', 'creator_id',
               existing_type=mysql.INTEGER(),
               comment='åˆ›å»ºè€…ID',
               existing_nullable=False)
    op.alter_column('exams', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='è€ƒè¯•æ\x8f\x8fè¿°',
               existing_nullable=True)
    op.alter_column('exams', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='è€ƒè¯•æ\xa0‡é¢˜',
               existing_nullable=False)
    op.alter_column('exam_records', 'status',
               existing_type=mysql.ENUM('in_progress', 'submitted', collation='utf8mb4_unicode_ci'),
               comment='è€ƒè¯•çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'in_progress'"))
    op.alter_column('exam_records', 'submit_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='æ\x8f\x90äº¤æ—¶é—´',
               existing_nullable=True)
    op.alter_column('exam_records', 'start_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='å¼€å§‹æ—¶é—´',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('exam_records', 'max_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='æ»¡åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'100.00'"))
    op.alter_column('exam_records', 'total_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='æ€»åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('exam_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('exam_records', 'exam_id',
               existing_type=mysql.INTEGER(),
               comment='è€ƒè¯•ID',
               existing_nullable=False)
    op.drop_constraint(None, 'exam_questions', type_='foreignkey')
    op.create_foreign_key(op.f('exam_questions_ibfk_1'), 'exam_questions', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exam_questions', 'order_index',
               existing_type=mysql.INTEGER(),
               comment='é¢˜ç›®é¡ºåº\x8f',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('exam_questions', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='é¢˜ç›®åˆ†å€¼',
               existing_nullable=True,
               existing_server_default=sa.text("'10.00'"))
    op.alter_column('exam_questions', 'station_id',
               existing_type=mysql.INTEGER(),
               comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('exam_questions', 'exam_id',
               existing_type=mysql.INTEGER(),
               comment='è€ƒè¯•ID',
               existing_nullable=False)
    op.drop_constraint(None, 'exam_answers', type_='foreignkey')
    op.create_foreign_key(op.f('exam_answers_ibfk_1'), 'exam_answers', 'exam_records', ['exam_record_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exam_answers', 'ai_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='AIè¯„ä»·å\x8f\x8dé¦ˆ',
               existing_nullable=True)
    op.alter_column('exam_answers', 'score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='å¾—åˆ†',
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('exam_answers', 'user_answer',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='ç”¨æˆ·ç\xad”æ¡ˆ',
               existing_nullable=True)
    op.alter_column('exam_answers', 'station_id',
               existing_type=mysql.INTEGER(),
               comment='ç«™ç‚¹ID',
               existing_nullable=False)
    op.alter_column('exam_answers', 'exam_record_id',
               existing_type=mysql.INTEGER(),
               comment='è€ƒè¯•è®°å½•ID',
               existing_nullable=False)
    op.alter_column('comments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comments', 'status',
               existing_type=mysql.ENUM('active', 'hidden', 'deleted', collation='utf8mb4_unicode_ci'),
               comment='çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('comments', 'likes_count',
               existing_type=mysql.INTEGER(),
               comment='ç‚¹èµžæ•°',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('comments', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment='çˆ¶è¯„è®ºID',
               existing_nullable=True)
    op.alter_column('comments', 'comment_type',
               existing_type=mysql.ENUM('comment', 'question', 'answer', 'suggestion', collation='utf8mb4_unicode_ci'),
               comment='è¯„è®ºç±»åž‹',
               existing_nullable=True,
               existing_server_default=sa.text("'comment'"))
    op.alter_column('comments', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='è¯„è®ºå†…å®¹',
               existing_nullable=False)
    op.alter_column('comments', 'content_id',
               existing_type=mysql.INTEGER(),
               comment='å…³è\x81”çš„ç\xad”æ¡ˆID',
               existing_nullable=False)
    op.alter_column('comments', 'content_type',
               existing_type=mysql.ENUM('station_answer', 'knowledge_answer', collation='utf8mb4_unicode_ci'),
               comment='è¯„è®ºå†…å®¹ç±»åž‹',
               existing_nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('comment_reports', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('comment_reports', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comment_reports', 'admin_note',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='ç®¡ç\x90†å‘˜å¤„ç\x90†æ„\x8fè§\x81',
               existing_nullable=True)
    op.alter_column('comment_reports', 'status',
               existing_type=mysql.ENUM('pending', 'reviewed', 'resolved', collation='utf8mb4_unicode_ci'),
               comment='å¤„ç\x90†çŠ¶æ€\x81',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('comment_reports', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='ä¸¾æŠ¥è¯¦æƒ…',
               existing_nullable=True)
    op.alter_column('comment_reports', 'reason',
               existing_type=mysql.ENUM('spam', 'inappropriate', 'offensive', 'other', collation='utf8mb4_unicode_ci'),
               comment='ä¸¾æŠ¥åŽŸå›\xa0',
               existing_nullable=False)
    op.alter_column('comment_reports', 'comment_id',
               existing_type=mysql.INTEGER(),
               comment='è¢«ä¸¾æŠ¥è¯„è®ºID',
               existing_nullable=False)
    op.alter_column('comment_reports', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='ä¸¾æŠ¥ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('comment_likes', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('comment_likes', 'comment_id',
               existing_type=mysql.INTEGER(),
               comment='è¯„è®ºID',
               existing_nullable=False)
    op.alter_column('comment_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='ç”¨æˆ·ID',
               existing_nullable=False)
    op.alter_column('cases', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('cases', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('cases', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='åŽŸå§‹æ–‡æ¡£è·¯å¾„',
               existing_nullable=True)
    op.alter_column('cases', 'site_info',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='ç«™ç‚¹ä¿¡æ\x81¯',
               existing_nullable=True)
    op.alter_column('cases', 'case_guide',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='æ¡ˆä¾‹æŒ‡å¼•',
               existing_nullable=True)
    op.alter_column('cases', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='æ¡ˆä¾‹æ\xa0‡é¢˜',
               existing_nullable=False)
    op.alter_column('cases', 'category_id',
               existing_type=mysql.INTEGER(),
               comment='ç±»åˆ«ID',
               existing_nullable=False)
    op.alter_column('case_categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('case_categories', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='ç±»åˆ«æ\x8f\x8fè¿°',
               existing_nullable=True)
    op.alter_column('case_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='ç±»åˆ«å\x90\x8dç§°',
               existing_nullable=False)
    op.alter_column('ai_settings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('ai_settings', 'zhipu_model',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='æ™ºè°±GLM æ¨¡åž‹',
               existing_nullable=True)
    op.alter_column('ai_settings', 'zhipu_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='æ™ºè°±GLM Key',
               existing_nullable=True)
    op.alter_column('ai_settings', 'openai_model',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='OpenAI æ¨¡åž‹',
               existing_nullable=True)
    op.alter_column('ai_settings', 'openai_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='OpenAI Key',
               existing_nullable=True)
    op.alter_column('ai_settings', 'provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='glm | openai | local',
               existing_nullable=False,
               existing_server_default=sa.text("'local'"))
    # ### end Alembic commands ###
