"""sync schema drift with models

Revision ID: e2865754a9a9
Revises: 94dc4402a203
Create Date: 2026-09-03 14:36:57.285135
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = 'e2865754a9a9'
down_revision = '94dc4402a203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 知识模块四张死表按「存在才删」处理：MySQL DDL 不可回滚，
    # 上次运行若中途失败已删掉部分表，重跑必须幂等
    from sqlalchemy import inspect as _inspect
    _existing = _inspect(op.get_bind()).get_table_names()
    for _t in ('knowledge_answers', 'knowledge_wrong_questions',
               'knowledge_learning_records', 'extended_knowledge'):
        if _t in _existing:
            op.drop_table(_t)
    op.add_column('ai_settings', sa.Column('accumulation_provider', sa.String(length=20), nullable=True))
    op.add_column('ai_settings', sa.Column('accumulation_key', sa.String(length=500), nullable=True))
    op.add_column('ai_settings', sa.Column('accumulation_model', sa.String(length=100), nullable=True))
    op.add_column('ai_settings', sa.Column('accumulation_embedding_model', sa.String(length=100), nullable=True))
    op.add_column('baidu_asr_keys', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ENUM 收窄（应用层已不再写入被移除的值）：
    # 若存量数据含 'knowledge_answer' / 'knowledge'，此 ALTER 会在 MySQL 上报错，
    # 需先人工清洗数据再升级（本库当前为空，直接生效）
    op.alter_column('comments', 'content_type',
               existing_type=mysql.ENUM('station_answer', 'knowledge_answer', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('station_answer'),
               existing_nullable=False)
    op.alter_column('point_records', 'related_type',
               existing_type=mysql.ENUM('learning', 'exam', 'knowledge', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('learning', 'exam'),
               existing_nullable=True)
    op.add_column('stations', sa.Column('condition_report', sa.Text(), nullable=True))
    # server_default 兜底存量行：ORM 侧 default 只作用于新插入，ALTER 存量表必须给 SQL 默认值
    op.add_column('stations', sa.Column('station_type', sa.Enum('assessment', 'knowledge'),
                                        nullable=False, server_default='assessment'))
    op.alter_column('stations', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=True)
    op.add_column('users', sa.Column('school', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('serial_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('consent_accepted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('consent_accepted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('knowledge_provider', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('knowledge_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('knowledge_model', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('knowledge_embedding_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'knowledge_embedding_model')
    op.drop_column('users', 'knowledge_model')
    op.drop_column('users', 'knowledge_key')
    op.drop_column('users', 'knowledge_provider')
    op.drop_column('users', 'consent_accepted_at')
    op.drop_column('users', 'consent_accepted')
    op.drop_column('users', 'serial_number')
    op.drop_column('users', 'school')
    op.alter_column('stations', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=False)
    op.drop_column('stations', 'station_type')
    op.drop_column('stations', 'condition_report')
    op.alter_column('point_records', 'related_type',
               existing_type=sa.Enum('learning', 'exam'),
               type_=mysql.ENUM('learning', 'exam', 'knowledge', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('comments', 'content_type',
               existing_type=sa.Enum('station_answer'),
               type_=mysql.ENUM('station_answer', 'knowledge_answer', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('baidu_asr_keys', 'updated_at')
    op.drop_column('ai_settings', 'accumulation_embedding_model')
    op.drop_column('ai_settings', 'accumulation_model')
    op.drop_column('ai_settings', 'accumulation_key')
    op.drop_column('ai_settings', 'accumulation_provider')
    op.create_table('extended_knowledge',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('extended_knowledge_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('knowledge_learning_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('knowledge_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_answer', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('max_score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ai_feedback', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['extended_knowledge.id'], name=op.f('knowledge_learning_records_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('knowledge_learning_records_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('knowledge_wrong_questions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('knowledge_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['extended_knowledge.id'], name=op.f('knowledge_wrong_questions_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('knowledge_wrong_questions_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('unique_user_knowledge'), 'knowledge_wrong_questions', ['user_id', 'knowledge_id'], unique=True)
    op.create_table('knowledge_answers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('knowledge_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_item', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('score_weight', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('order_index', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['extended_knowledge.id'], name=op.f('knowledge_answers_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
